development:
    dialect: postgres
    datasource: host=localhost port=5432 dbname=temporal user=temporal password=temporal sslmode=disable
    dir: migrations
    table: migrations

production:
    dialect: postgres
    datasource: host=localhost port=5432 dbname=${DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
    dir: database/migrations
    table: migrations
